services:
  clothingstorebenet:
    image: ${DOCKER_REGISTRY-}clothingstorebenet
    build:
      context: .
      dockerfile: ClothingStoreBENET/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
  clothingstorebe.database:
    image: postgres:latest
    container_name: clothingstorebe.database
    environment:
        - POSTGRES_DB=ClothingStore
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=lhs00000
    ports:
        - 5432:5432 
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis-containers
    ports: 
        - "6379:6379"
    volumes:
        - redis-data:/data

volumes:
  db-data:
    name: clothingStoreBE
  redis-data:
